# Вывод из task30
> Ошибка в 3-ем тесте допущена специально

test1(com.company.task30.RegexTest) : test passed<br/>test2(com.company.task30.RegexTest) : test passed<br/>test3(com.company.task30.RegexTest) : test failed : java.lang.AssertionError: expected: true but was: false<br/>test4(com.company.task30.RegexTest) : test passed<br/>